# Generated by Django 6.0.3 on 2026-03-31 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('belt', models.CharField(blank=True, max_length=50, verbose_name='Пояс')),
                ('weight_category', models.CharField(blank=True, max_length=50, verbose_name='Весовая категория')),
                ('sport_category', models.CharField(blank=True, max_length=50, verbose_name='Спортивная категория')),
                ('competitions_count', models.PositiveIntegerField(default=0, verbose_name='Количество соревнований')),
                ('wins_count', models.PositiveIntegerField(default=0, verbose_name='Количество побед')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
