# Generated by Django 6.0.3 on 2026-04-20 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_status', to='students.studentprofile', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Статус оплаты',
                'verbose_name_plural': 'Статусы оплаты',
            },
        ),
    ]
