# Generated by Django 6.0.3 on 2026-04-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentstatus',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='paymentstatus',
            name='paid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Оплачено до'),
        ),
    ]
